### PR TITLE
Porting to Pennylane 0.36 and JAX/JAXlib 0.4.26

### PR DESCRIPTION
**Pull request by drelu**
Pennylane 0.36 and JAX/JAXlib 0.4.26 support
Both are CUDA12 and compatible now

### CODE REVIEW

**Comment by pradeepmantha** [comment]
Minor: Please update the readme to reflect new jax version changes.

**Comment by aleksandar-vuckovic** [comment]
PR #3 already bumps JAX to 0.4.26 and updates several other packages. Also, I don't think it's necessary to install `pennylane-lightning` as we currently are only using the `default.qubit` and `default.qubit.jax` backends for continuous and discrete model handlers, respectively.

**Comment by drelu** [comment]
@aleksandar-vuckovic: When are you planning to merge PR #3 into main?

**Comment by aleksandar-vuckovic** [comment]
@drelu I was waiting on the explicit approval by any of the other maintainers. Regardless, given the necessity, PR #3 has now been merged.

**Pull request closed without merging**
